name: Build and Release

on:
  release:
    types: [created]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Get version tag
        id: get_version
        run: echo ::set-output name=version::$(echo $GITHUB_REF | sed 's/refs\/tags\///')
      - name: Get version count
        id: get_version_count
        run: echo ::set-output name=version_count::$(git tag | wc -l)

      - name: Set version code
        run: sed -i "s/versionCode 1/versionCode ${{ steps.get_version_count.outputs.version_count }}/g" android/app/build.gradle
      - name: Set version name
        run: sed -i "s/versionName \"1.0\"/versionName \"${{ steps.get_version.outputs.version }}\"/g" android/app/build.gradle

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19.x

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm i

      - name: Build web app
        run: pnpm build

      - name: Build app bundle
        run: cd android && ./gradlew bundle && ./gradlew assembleDebug

      - name: Extract Android signing key from env
        run: |
          echo "${{ secrets.RELEASE_KEYSTORE }}" > android/release.jks.base64
          base64 -d android/release.jks.base64 > android/release.jks

      - name: Sign dev build
        run: jarsigner -keystore android/release.jks -storepass "${{ secrets.RELEASE_KEYSTORE_PASSWORD }}" -signedjar ./android/app/build/outputs/bundle/release/app-release-signed.aab ./android/app/build/outputs/bundle/release/app-release.aab release

      - name: List release files
        run: ls ./android/app/build/outputs/bundle/release

      - name: Upload APK to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ./android/app/build/outputs/apk/debug/app-debug.apk

      - name: Upload AAB to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-release-signed
          path: ./android/app/build/outputs/bundle/release/app-release-signed.aab

      - uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          releaseName: ${{ steps.get_version.outputs.version }}
          packageName: me.scolastico.dyn.redirect
          releaseFiles: |
            ./android/app/build/outputs/bundle/release/app-release-signed.aab
